// Shared data and helpers for Dr. Promilton's site
window.SITE_DATA = {
  name: {
    first: "Dr. A. Antony Alosanai",
    last: "Promilton",
    short: "Dr. Promilton",
  },
  titles: ["Ph.D.", "Hydrogeologist", "Consultant Geophysicist", "Geospatial Researcher"],
  tagline: "Mapping water beneath hard-rock terrain — where geophysics, geochemistry and geospatial science meet.",
  contact: {
    email: "geopromilton@gmail.com",
    phones: ["+91 99623 53227", "+91 82481 28907"],
    address: "3/25, Antoniar Kebi Street, Mela Arasadi Po., Vellapatti, Thoothukudi, Tamil Nadu – 628002, India",
    orcid: "0000-0002-6762-0103",
    scholar: "kkKsxrYAAAAJ",
  },
  stats: [
    { n: "22", label: "Journal Articles" },
    { n: "7", label: "Book Chapters" },
    { n: "45+", label: "Citations" },
    { n: "3", label: "h-Index" },
    { n: "3", label: "Journals Reviewed" },
  ],
  bio: [
    "Dr. A. Antony Alosanai Promilton is a hydrogeologist and consultant geophysicist based in Thoothukudi, Tamil Nadu, whose research sits at the intersection of subsurface geophysics, hydrogeochemistry, and geospatial analysis. His doctoral work at Manonmaniam Sundaranar University developed an integrated framework — Azimuthal Square Array resistivity, VES, 3D lithological modelling and seasonal geochemistry — for characterising fractured hard-rock aquifers in the Valliyur region of southern Tamil Nadu.",
    "Across 22 peer-reviewed papers in journals including Scientific Reports, Environmental Geochemistry and Health, and Water Conservation Science and Engineering, his work advances sustainable groundwater management in water-stressed crystalline terrains and coastal zones. As a consultant with Imman Geotech, he translates research into field practice — well-site investigation, aquifer characterisation, and renewable-energy suitability mapping — and serves as a peer reviewer for three international hydrology journals.",
  ],
  interests: [
    "Hydrogeology & groundwater exploration",
    "Applied geophysics · VES · ASAR · ERT · AMT/ADMT",
    "Coastal hydrogeology",
    "Hard-rock aquifer characterisation",
    "Hydrogeochemistry & water quality",
    "GIS, remote sensing & geospatial analysis",
    "MCDA · AHP · TOPSIS",
    "Machine learning in hydrology",
    "Sediment geochemistry & marine studies",
    "Disaster vulnerability mapping",
    "Sustainable water resource management",
    "Renewable energy site selection",
  ],
  education: [
    {
      degree: "Ph.D. in Geology",
      inst: "Manonmaniam Sundaranar University, Tirunelveli",
      year: "2025",
      note: "Thesis: Groundwater Investigations Using Azimuthal Square Array Method and Geochemical Modelling in Hard Rock Terrain, Valliyur Region, Tamil Nadu. Guide: Dr. A. Antony Ravindran.",
    },
    {
      degree: "M.Sc. Geology",
      inst: "V.O. Chidambaram College, Thoothukudi",
      year: "2017",
      note: "79% · Distinction",
    },
    {
      degree: "B.Sc. Geology",
      inst: "V.O. Chidambaram College, Thoothukudi",
      year: "2015",
      note: "78% · Distinction",
    },
  ],
  experience: [
    {
      role: "Consultant Geologist / Geophysicist",
      org: "Imman Geotech Pvt. Ltd., Thoothukudi",
      from: "Mar 2021",
      to: "Present",
      kind: "Consultant",
      desc: "Well-site geophysical investigation, aquifer characterisation, and groundwater suitability mapping for agricultural and coastal-industrial clients.",
    },
    {
      role: "Subject Matter Expert — Earth Sciences",
      org: "Chegg India Pvt. Ltd.",
      from: "Aug 2018",
      to: "Mar 2025",
      kind: "Freelance",
      desc: "Expert solutions across hydrogeology, structural geology, geomorphology and remote sensing for a global question bank.",
    },
    {
      role: "Hydrogeologist",
      org: "Ratnam Energy Pvt. Ltd., Gujarat",
      from: "Jul 2017",
      to: "Aug 2018",
      kind: "Full-time",
      desc: "Field hydrogeology and site suitability for energy infrastructure in the Saurashtra region.",
    },
  ],
  skills: [
    {
      group: "Hydrogeology & Groundwater",
      items: [
        "Groundwater flow analysis · aquifer characterisation · storage dynamics",
        "Pumping, slug & recovery tests — transmissivity & storativity",
        "Well drilling supervision · lithological logging · geochemical sampling",
      ],
    },
    {
      group: "Geophysical Surveying",
      items: [
        "VES · Azimuthal Square Array (ASAR) · ERT · AMT/ADMT",
        "Fracture orientation mapping · secondary porosity estimation",
        "Subsurface lithological & 3D aquifer modelling",
      ],
    },
    {
      group: "Hydrogeochemistry & Water Quality",
      items: [
        "Major ions · trace elements · heavy metal determination",
        "WQI · DRASTIC · contamination factor · health-risk assessment",
        "PCA · HCA · multivariate statistics",
      ],
    },
    {
      group: "GIS, RS & Geospatial",
      items: [
        "ArcGIS · QGIS · Google Earth Engine · ERDAS Imagine",
        "AHP · TOPSIS for GWPZ, suitability & LULC change",
        "HEC-HMS · HEC-RAS · MODFLOW · GMS modelling",
      ],
    },
    {
      group: "Programming & ML",
      items: [
        "Python · Google Colab",
        "Random Forest · XGBoost · SVM · SHAP · CA-Markov",
      ],
    },
    {
      group: "Sediment & Marine",
      items: [
        "Marine sediment sampling",
        "Grain-size & heavy-mineral analysis",
        "Organic matter characterisation",
      ],
    },
  ],
  publications: [
    {n:1, year:"2026", authors:"Abishek, S.R., Pitchaimani, V.S., Ravindran, A.A., Priya, R.S., Kaliraj, S., Promilton, A.A.A. & Joe, R.J.J.", title:"Integrated assessment of soil and rock penetration across the crystalline basement of the lower Thamirabarani river basin, southern India", venue:"Discover Civil Engineering 3, 68", doi:"10.1007/s44290-026-00451-9", tags:["hydro","gis"]},
    {n:2, year:"2026", authors:"Pitchaimani, V.S., Joe, R.J.J., Stuvar, S.S.R., Liberthin, M., Promilton, A.A.A. & Abishek, S.R.", title:"Landslide susceptibility and vulnerability assessment using GIS–AHP in the highland of Wayanad, Western Ghats, India", venue:"Discover Hazards 2, 5", doi:"10.1007/s44475-026-00008-5", tags:["gis","disaster"]},
    {n:3, year:"2026", authors:"Pitchaimani, V.S., Abishek, S.R., Joe, R.J.J. & Promilton, A.A.A.", title:"Seasonal variations of inner shelf sediment dynamics and granulometric characteristics along the Nagapattinam coast of the Cauvery basin, Southern India", venue:"Discover Oceans 3, 4", doi:"10.1007/s44289-025-00109-x", tags:["coastal","sediment"]},
    {n:4, year:"2026", authors:"Abishek, S.R., Pitchaimani, V.S., Kaliraj, S., Priya, R.S., Ravindran, A.A., Promilton, A.A.A. & Karuppannan, S.", title:"Hydrogeochemical variability and health risk assessment of heavy metals in groundwater of Srivaikundam region, Southern India", venue:"Environmental Geochemistry and Health 48, 37", doi:"10.1007/s10653-025-02914-x", tags:["hydro","geochem"]},
    {n:5, year:"2025", authors:"Grace, C.A.Z., Soundranayagam, J.P., Sidhu, N., et al. & Promilton, A.A.A.", title:"Decadal dynamics of urban heat islands in a coastal industrial region of India: remote sensing insights for sustainable urban planning", venue:"Environment, Development and Sustainability", doi:"10.1007/s10668-025-07153-9", tags:["gis","coastal"]},
    {n:6, year:"2025", authors:"Ramachandran, A., Promilton, A.A.A., Pitchaimani, V.S., et al.", title:"Provenance and coastal dynamics inferred through textural parameters and heavy mineral contents of the shoreline sediments, Tamil Nadu, southeast India", venue:"J. Indian Assoc. Sedimentologists 42(II), 34–51", doi:"10.51710/jias.v42iI.445", tags:["coastal","sediment"]},
    {n:7, year:"2025", authors:"Grace, C.A.Z., Soundranayagam, J.P., et al. & Promilton, A.A.A.", title:"Quantifying spatiotemporal LULC change and urban expansion using geospatial modelling and Shannon's entropy in a coastal city of India", venue:"Discover Civil Engineering 2, 189", doi:"10.1007/s44290-025-00341-6", tags:["gis","coastal"]},
    {n:8, year:"2025", authors:"Joe, R.J.J., Pitchaimani, V.S., Kaliraj, S., Abishek, S.R., Promilton, A.A.A. & Karuppannan, S.", title:"Spatial modelling of groundwater potential zones in the Neyyar Basin using machine learning and morphometric analysis", venue:"Scientific Reports 15, 36171", doi:"10.1038/s41598-025-20000-1", tags:["hydro","ml","gis"]},
    {n:9, year:"2025", authors:"Promilton, A.A.A., Ravindran, A.A., Pitchaimani, V.S., Kingston, J.V., Abishek, S.R. & Joe, R.J.J.", title:"Characterization of fractured basement aquifers using Square Array VES, azimuthal resistivity analysis and 3D lithological modelling: an integrated approach for sustainable groundwater management", venue:"Water Conservation Science and Engineering 10, 114", doi:"10.1007/s41101-025-00444-2", tags:["hydro","geophys"], featured:true},
    {n:10, year:"2025", authors:"Grace, C.A.Z., Soundranayagam, J.P., Promilton, A.A.A., et al.", title:"Integrating remote sensing and geospatial-based comprehensive MCDA approach for sustainable coastal solar site selection in southern India", venue:"ISPRS Int. J. Geo-Information 14, 377", doi:"10.3390/ijgi14100377", tags:["gis","energy"]},
    {n:11, year:"2025", authors:"Promilton, A.A.A., Ravindran, A.A., Pitchaimani, V.S., Kingston, J.V. & Karuppannan, S.", title:"Comprehensive hydrogeochemical characterization and seasonal water quality index analysis for sustainable groundwater management in Valliyur region, Southern Tamil Nadu, India", venue:"Scientific Reports 15, 33251", doi:"10.1038/s41598-025-18285-3", tags:["hydro","geochem"], featured:true},
    {n:12, year:"2025", authors:"Abishek, S.R., Ravindran, A.A., Pitchaimani, V.S., Kaliraj, S., Kingston, J.V., Promilton, A.A.A. & Joe, R.J.J.", title:"Hydrogeophysical characterization of groundwater and subsurface geology using VES and GMS modeling in Srivaikundam region, Southern Tamil Nadu", venue:"Modeling Earth Systems and Environment 11, 339", doi:"10.1007/s40808-025-02542-5", tags:["hydro","geophys"]},
    {n:13, year:"2025", authors:"Grace, C.A.Z., Soundranayagam, J.P., Promilton, A.A.A. & Pitchaimani, V.S.", title:"Mapping of cyclone disaster vulnerability using geospatial techniques and AHP: implications for resilient urban planning in coastal city of Southern Tamil Nadu", venue:"Disaster Advances 18(7), 50–60", doi:"10.25303/187da050060", tags:["disaster","gis","coastal"]},
    {n:14, year:"2025", authors:"Aswin, S.K., Pitchaimani, V.S. & Promilton, A.A.A.", title:"Flood susceptibility assessment for coastal villages of Southern Tamil Nadu: an integrated GIS and AHP approach", venue:"Disaster Advances 18(6), 18–27", doi:"10.25303/186da018027", tags:["disaster","gis"]},
    {n:15, year:"2025", authors:"Priya, R.S., Ravindran, A.A., Abishek, S.R., et al. & Promilton, A.A.A.", title:"Remote sensing and GIS for groundwater potential zones for sustainable urban development in coastal areas between Chettikulam and Kolachal, southern India", venue:"Applied Geomatics", doi:"10.1007/s12518-024-00604-4", tags:["gis","hydro","coastal"]},
    {n:16, year:"2024", authors:"Grace, C.A.Z., Soundranayagam, J.P., Promilton, A.A.A. & Pitchaimani, V.S.", title:"Synergizing hazard resilience and renewable energy potential for smart coastal development: a GIS-MCDA approach in Thoothukudi, India", venue:"Nanotechnology Perceptions 20(S13), 2608–2628", doi:"", tags:["gis","energy","coastal"]},
    {n:17, year:"2024", authors:"Ravindran, A.A., Promilton, A.A.A., Kingston, J.V., Abishek, S.R., Abinaya, R. & Priya, R.S.", title:"Multicriteria analysis of groundwater potential in Valliyur region, Tamil Nadu: integrating remote sensing, GIS and AHP", venue:"Water Conservation Science and Engineering 9, 53", doi:"10.1007/s41101-024-00285-5", tags:["gis","hydro"], featured:true},
    {n:18, year:"2024", authors:"Ravindran, A.A., Abinaya, R., Abishek, S.R., Kingston, J.V., Promilton, A.A.A. & Priya, R.S.", title:"Geophysical exploration of tectonic signatures in Proterozoic quartzite of the Kovilpatti region, Southern India", venue:"Carbonates and Evaporites 39, 59", doi:"10.1007/s13146-024-00962-5", tags:["geophys"]},
    {n:19, year:"2024", authors:"Ravindran, A.A., Promilton, A.A.A., Kingston, J.V., et al.", title:"Geophysical and geochemical studies on sinking stream occurrence in Ayankulam village of South Tamil Nadu, India", venue:"Proc. Indian National Science Academy", doi:"10.1007/s43538-024-00287-w", tags:["geophys","geochem"]},
    {n:20, year:"2022", authors:"Ravindran, A.A. & Promilton, A.A.A.", title:"Geophysical and geochemical prospecting for submarine groundwater discharge in a karst leaky aquifer from Valliyur Hills to Uvari Beach", venue:"Modeling Earth Systems and Environment 8, 4909–4921", doi:"10.1007/s40808-022-01412-8", tags:["coastal","geophys","geochem"]},
    {n:21, year:"2022", authors:"Kingston, J.V., Ravindran, A.A., Abishek, S.R., Aswin, S.K. & Promilton, A.A.A.", title:"Integrated geophysical and geochemical assessment of submarine groundwater discharge in coastal terrace of Tiruchendur, Southern India", venue:"Applied Water Science 12, 9", doi:"10.1007/s13201-021-01553-8", tags:["coastal","hydro"]},
    {n:22, year:"2020", authors:"Jeyapaul, V.K., Antony Jebamalai, A.R., Selvam, R.A., Krishnaveni, A.S. & Antony Johnson, A.A.P.", title:"A case study of freshwater discharge in porous calcarenite formation in coastal terrace at Manapad, South India", venue:"Carbonates and Evaporites 35, 114", doi:"10.1007/s13146-020-00641-1", tags:["coastal","hydro"]},
  ],
  bookChapters: [
    {title:"Interacting RS and GIS to GWPZ in Urban Development Site Suitability Analysis of Kovilpai Region, Southern Tamil Nadu, India", authors:"Rajendran, A., Ravindran, A., Promilton, A.A., Ganesan, S.", year:"2025"},
    {title:"Groundwater Exploration in Fractured Charnockite Formation for Irrigation at Alangulam, Tamil Nadu, India", authors:"Promilton, A.A., Ravindran, A., Afzal, M., Rajendran, A.", year:"2024"},
    {title:"Groundwater Management Studies Using Geological and 2D ERI Techniques in Ariyanayakipuram Village, Tirunelveli, Tamil Nadu, India", authors:"Ravindran, A., Kingston, J.V., Samy, M., Promilton, A.A., Rajendran, A.", year:"2023"},
    {title:"Groundwater Exploration Study using 2D ERI and Geochemical Mapping in Muruganpuram, Vallanadu, Tamil Nadu", authors:"Abishek, S.R., et al.", year:"CESS–2022", pages:"pp. 66–70"},
    {title:"Freshwater discharge in coastal aquifer study using electrical resistivity and geochemical method in Sahupuram, Thoothukudi", authors:"Kingston, J.V., et al.", year:"CESS–2022", pages:"pp. 50–56"},
    {title:"Crystalline limestone investigation study in Podupatti and Pungarvattam, Ettayapuram, Thoothukudi", authors:"Kanagaraj, R., et al.", year:"CESS–2022", pages:"pp. 134–138"},
    {title:"Crystalline limestone investigation study in Podupatti and Pungarvattam, Ettayapuram, Thoothukudi", authors:"Promilton, A.A., et al.", year:"CESS–2022", pages:"pp. 134–138"},
  ],
  conferences: [
    {title:"Signature of Sinking Streams on Calcarenite Rock Study Using Geophysical and Geochemical Investigation in Ayankulam Area, South Tamil Nadu, India", venue:"ICRAWST-2022", date:"December 2022", kind:"International"},
    {title:"Exploration of Ground Water Using Azimuthal Square Array Method and Magneto Telluric Method in Quartzite Rich Terrain of Pudukkottai, Tamil Nadu", venue:"CESS-2022", date:"2022", kind:"International"},
  ],
  reviewing: [
    "Environmental Monitoring and Assessment",
    "Groundwater for Sustainable Development",
    "Sustainable Water Resources Management",
  ],
  awards: [
    {title:"Best Researcher Award in Earth and Planetary Sciences", issuer:"Book of Award", date:"September 2025"},
    {title:"Associate Student Member (ID 145289)", issuer:"International Association of Hydrogeologists (IAH)", date:"Since August 2024"},
  ],
  // Approximate coordinates for field sites mentioned in publications (Tamil Nadu focus)
  fieldSites: [
    {name:"Valliyur", x:0.28, y:0.82, role:"PhD field area · fractured basement aquifers"},
    {name:"Thoothukudi", x:0.40, y:0.74, role:"Home base · coastal industrial studies"},
    {name:"Tiruchendur", x:0.40, y:0.80, role:"Submarine groundwater discharge"},
    {name:"Uvari Beach", x:0.30, y:0.88, role:"Karst leaky aquifer"},
    {name:"Srivaikundam", x:0.36, y:0.72, role:"Hydrogeochemistry · heavy metals"},
    {name:"Kovilpatti", x:0.33, y:0.62, role:"Proterozoic quartzite tectonics"},
    {name:"Ayankulam", x:0.32, y:0.78, role:"Sinking streams · calcarenite"},
    {name:"Manapad", x:0.44, y:0.80, role:"Calcarenite freshwater discharge"},
    {name:"Nagapattinam", x:0.58, y:0.46, role:"Inner-shelf sediment dynamics"},
    {name:"Neyyar Basin", x:0.18, y:0.88, role:"ML · GWPZ modelling"},
    {name:"Chettikulam–Kolachal", x:0.22, y:0.92, role:"Coastal GWPZ"},
    {name:"Wayanad", x:0.14, y:0.55, role:"Landslide susceptibility"},
    {name:"Pudukkottai", x:0.50, y:0.45, role:"ASAR & MT in quartzite"},
    {name:"Alangulam", x:0.26, y:0.72, role:"Charnockite aquifers"},
    {name:"Saurashtra, Gujarat", x:0.02, y:0.20, role:"Early career hydrogeology"},
  ],
  timeline: [
    {year:"2015", kind:"edu", title:"B.Sc. Geology", note:"V.O. Chidambaram College · 78%"},
    {year:"2017", kind:"edu", title:"M.Sc. Geology", note:"V.O. Chidambaram College · 79% (Dist.)"},
    {year:"2017", kind:"work", title:"Hydrogeologist", note:"Ratnam Energy, Gujarat"},
    {year:"2018", kind:"work", title:"SME — Earth Sciences", note:"Chegg India"},
    {year:"2021", kind:"work", title:"Consultant Geologist / Geophysicist", note:"Imman Geotech, Thoothukudi"},
    {year:"2022", kind:"pub", title:"First-author SGD paper", note:"Modeling Earth Systems & Env."},
    {year:"2024", kind:"award", title:"IAH Membership", note:"Int'l Assoc. of Hydrogeologists"},
    {year:"2025", kind:"edu", title:"Ph.D. awarded", note:"Manonmaniam Sundaranar University"},
    {year:"2025", kind:"award", title:"Best Researcher Award", note:"Earth & Planetary Sciences"},
    {year:"2026", kind:"pub", title:"22nd indexed paper", note:"Discover Civil Engineering"},
  ],
};
